known_languages = {
    'en', 'de', 'fr', 'es', 'it', 'jp', 'zh', 'ru', 'pt', 'nl', 'sv', 'pl', 'ja',
    'vi', 'war', 'ceb', 'ar', 'sr', 'no', 'fi', 'uk', 'cs', 'hu', 'da', 'kk', 'sk',
    'he', 'bg', 'ko', 'id', 'tr', 'ro', 'fa', 'eu', 'ca', 'ms', 'eo', 'hy', 'th',
    'bs', 'hr', 'lt', 'sl', 'et', 'gl', 'nn', 'az', 'el', 'simple', 'la', 'vo',
    'be', 'is', 'lv', 'hi', 'ht', 'ga', 'sq', 'ka', 'br', 'tg', 'cy', 'mk', 'new',
    'ml', 'th', 'pms', 'tl', 'te', 'ta', 'pnb', 'ast', 'oc', 'ky', 'bn', 'jv', 'mn',
    'sh', 'mt', 'lv', 'tl', 'tg', 'ky', 'tt', 'tk', 'gv', 'ie', 'kw', 'csb', 'scn',
    'stq', 'nds', 'ku', 'ast', 'af', 'an', 'ang', 'arz', 'ast', 'azb', 'ba', 'bar',
    'bat-smg', 'bcl', 'be-x-old', 'bh', 'bi', 'bjn', 'bm', 'bo', 'bpy', 'bug',
    'bxr', 'cbk-zam', 'cdo', 'ce', 'ceb', 'ch', 'cho', 'chr', 'chy', 'ckb', 'cr',
    'crh', 'csb', 'cu', 'cv', 'diq', 'dsb', 'dty', 'dz', 'ee', 'eml', 'ff', 'fiu-vro',
    'fj', 'fo', 'frp', 'frr', 'fur', 'fy', 'gag', 'gan', 'gd', 'glk', 'gn', 'gom',
    'gor', 'got', 'gu', 'gv', 'ha', 'hak', 'haw', 'hif', 'ho', 'hsb', 'ht', 'hu',
    'hup', 'hyw', 'hz', 'ia', 'ie', 'ig', 'ii', 'ik', 'ilo', 'inh', 'io', 'iu',
    'jam', 'jbo', 'jv', 'kaa', 'kab', 'kbd', 'kbp', 'kg', 'ki', 'kj', 'kr', 'krc',
    'kri', 'krj', 'krl', 'ks', 'ksh', 'ku', 'kv', 'kw', 'lad', 'lb', 'lbe', 'lez',
    'lg', 'li', 'lij', 'lmo', 'ln', 'lo', 'lrc', 'ltg', 'lus', 'lzz', 'mai', 'map-bms',
    'mdf', 'mg', 'mh', 'mi', 'min', 'mk', 'mn', 'mo', 'mrj', 'ms', 'mt', 'mus', 'mwl',
    'my', 'myv', 'mzn', 'na', 'nah', 'nap', 'nds', 'ne', 'new', 'ng', 'nia', 'niu',
    'nqo', 'nrm', 'nso', 'nv', 'ny', 'oc', 'olo', 'om', 'or', 'os', 'pag', 'pam',
    'pap', 'pdc', 'pfl', 'pi', 'pih', 'pl', 'pms', 'pnb', 'pnt', 'ps', 'pt', 'qu',
    'rm', 'rmy', 'rn', 'roa-rup', 'roa-tara', 'rw', 'sa', 'sah', 'sat', 'sc', 'scn',
    'sco', 'sd', 'se', 'sg', 'shn', 'si', 'simple', 'sli', 'sm', 'sn', 'so', 'sq',
    'srn', 'ss', 'st', 'stq', 'su', 'sv', 'sw', 'szl', 'ta', 'tcy', 'te', 'tet',
    'tg', 'ti', 'tk', 'tl', 'tn', 'to', 'tpi', 'tr', 'ts', 'tt', 'tum', 'tw', 'ty',
    'tyv', 'udm', 'ug', 'uk', 'ur', 'uz', 've', 'vec', 'vep', 'vi', 'vls', 'vo',
    'wa', 'war', 'wo', 'wuu', 'xal', 'xh', 'xmf', 'yi', 'yo', 'za', 'zea', 'zh',
    'zh-classical', 'zh-min-nan', 'zh-yue', 'zu', 'wikidata', 'km', 'be-tarask', 'div',
    'kn', 'als', 'pa', 'as'
}
